import type { MetadataRoute } from "next";
import { SITE_URL } from "@/lib/seo";

// robots.txt — generated by Next.js at /robots.txt.
//
// We explicitly welcome AI answer-engine crawlers (GEO): being cited by
// Perplexity, ChatGPT Search, Gemini, and Claude requires letting their bots in.
// Personal, wallet-gated routes are disallowed to keep them out of the index.
export default function robots(): MetadataRoute.Robots {
  const aiCrawlers = [
    "GPTBot", // OpenAI (ChatGPT)
    "OAI-SearchBot", // ChatGPT Search
    "ChatGPT-User",
    "PerplexityBot",
    "Perplexity-User",
    "ClaudeBot", // Anthropic
    "Claude-Web",
    "anthropic-ai",
    "Google-Extended", // Google Gemini / AI Overviews
    "Applebot-Extended",
    "CCBot", // Common Crawl (feeds many LLMs)
    "cohere-ai",
    "Bytespider",
    "Meta-ExternalAgent",
  ];

  return {
    rules: [
      {
        userAgent: "*",
        allow: "/",
        disallow: ["/my-listings", "/api/"],
      },
      // Give the AI crawlers an explicit, unambiguous allow.
      {
        userAgent: aiCrawlers,
        allow: "/",
        disallow: ["/my-listings", "/api/"],
      },
    ],
    sitemap: `${SITE_URL}/sitemap.xml`,
    host: SITE_URL,
  };
}
