import type { MetadataRoute } from "next";
import { SITE_URL } from "@/lib/seo";

// XML sitemap — generated by Next.js at /sitemap.xml.
// Only public, indexable routes (my-listings is wallet-gated → excluded).
export default function sitemap(): MetadataRoute.Sitemap {
  const routes: {
    path: string;
    priority: number;
    changeFrequency: MetadataRoute.Sitemap[number]["changeFrequency"];
  }[] = [
    { path: "/", priority: 1.0, changeFrequency: "daily" },
    { path: "/marketplace", priority: 0.9, changeFrequency: "hourly" },
    { path: "/activity", priority: 0.7, changeFrequency: "hourly" },
    { path: "/docs", priority: 0.6, changeFrequency: "weekly" },
  ];

  return routes.map((r) => ({
    url: r.path === "/" ? SITE_URL : `${SITE_URL}${r.path}`,
    lastModified: new Date(),
    changeFrequency: r.changeFrequency,
    priority: r.priority,
  }));
}
